# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-05 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180305_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 14, 35, 8, 696717, tzinfo=utc), verbose_name='保存日期'),
        ),
    ]
