# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-05 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180305_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 22, 38, 14, 499876), verbose_name='保存日期'),
        ),
    ]
